replicaCount: 1

appLabel: temp

image:
  repository: ahmed377/apptemp
  tag: v7

appService:
  type: NodePort
  nodePort: 32001
  port: 5002

versionApp:
  name: version
  image: ahmed377/appversion
  containerPort: 5003
  replicas: 1

versionService:
  type: NodePort
  nodePort: 30001
  port: 5003
  targetPort: 5003

versionIngress:
  host: "hivebox-version.local"

ingress:
  host: "hivebox-app.local"

