nd-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  
  - role: control-plane
    image: kindest/node:v1.27.3  
    extraPortMappings:
       - containerPort: 80
         hostPort: 8080
         protocol: TCP
    
  # Worker Node 1
  - role: worker
     image: kindest/node:v1.27.3  

  # Worker Node 2
  - role: worker
    image: kindest/node:v1.27.3  
    
