apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30091

