apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hiveboxapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aaabaza761/HiveBox-Project.git
    path: hivebox-charts
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
