name: ci pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #check out 
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: install Hadolint 
        run: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /bin/hadolint
      
      - name: lint Dockerfile in Versio
        run: hadolint Version/Dockerfile

      - name: lint Dockerfile in temp
        run: hadolint Temp/Dockerfile

        