name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install Hadolint
      - name: Install Hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/hadolint

      # Lint Dockerfiles
      - name: Lint Dockerfile in Version
        run: hadolint Version/Dockerfile

      - name: Lint Dockerfile in Temp
        run: hadolint Temp/Dockerfile

      # Install pylint
      - name: Install pylint
        run: pip install pylint

      # Set PYTHONPATH and Run pylint
      - name: Use pylint to check code
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pylint Version/*.py Temp/*.py tests/*.py || exit 0

        
