name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #checkout the code
      - name: checkout the code ( clone on server ubuntu )
        uses: actions/checkout@v4
      
      #Lint the Dockerfile
      - name: lint Dockerfile in Temp
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Temp/Dockerfile
      
      # RUN Ready Pylint action 
      - name: use pylint to check code
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "Temp Version tests"
          use-pylint: true
          extra-pylint-options: "--exit-zero"

  test:
    runs-on: ubuntu-latest
    steps:
      #checkout the code
      - uses: actions/checkout@v4
      
      #set-up pyhon
      - name: set-up python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      
      #install dependencies
      - name: install dependencies
        run: pip install -r Temp/requirements.txt
             
      
      #run test
      - name: run unt tests
        run: python -m unittest discover -s tests -p "test_app_temp.py"

  
  build:
    runs-on: ubuntu-latest
    steps:
      #checkout the code
      - name: checkout the code
        uses: actions/checkout@v4
      - name: List project files
        run: ls -R
      
      #build, tag using secrets credentialon Dockerhub and push the image 
      - name: Build, Tag & Publish Image to DockerHub
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: Temp
          file: Temp/Dockerfile
          repoOwner: ${{ secrets.DOCKER_USERNAME }}
          repository:  apptemp
          tag: 11
  
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of code
        uses: actions/checkout@v3

      - name: run Openssf Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.json
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Scorecard results
          path: results.json